# Site settings
title: M. Ueno's Homepage
description: Website about M. Ueno(eunos-1128)
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: M. Ueno
user_description: I am engineering researcher living in Japan. My specialty is Bioinformatics, Cheminformatics and Web Development. In the university and graduate school I studied chemistry, pharmaceutical science and neurobiology.
user_title: Engineering Researcher &#x1f4bb;
email: eunosium-1128@live.jp
twitter_username: lorem_ipsum
github_username: eunos-1128

# Google-analytics
google-analytics:
  id: ""

exclude: ["package.json", "src", "node_modules"]
